Development checkpoint.

diff --git a/apk/podman_setup b/apk/podman_setup
--- a/apk/podman_setup
+++ b/apk/podman_setup
@@ -28,4 +28,17 @@ if ! grep '^containers:' /etc/subuid /etc/subgid ; then
   printf '%s\n' 'containers:100000:65536' | doas tee -a /etc/subgid
 fi
 
+for x in subuid subgid ; do
+  target="/etc/$x"
+  origin"$HOME/config/root/etc_$x"
+  if test -e "$origin" ; then
+    err "Not found: $origin"
+  fi
+
+  if ! diff "$origin" "$target" ; then
+    tell "Installing: $target ..."
+    doas install -o root -g root "$origin" "$target"
+  fi
+done
+
 tun_setup
